backend:
    name: github
    repo: alemarcha/elemental-blog
    site_domain: zealous-swanson-b611d2.netlify.com

media_folder: "contents/blog/assets"
public_folder: "/assets"

# Uncomment to leverage Netlify CMS UI authoring flow
# see: https://www.netlifycms.org/docs/configuration-options/#publish-mode
# publish_mode: editorial_workflow

collections:
    - name: "blog"
      label: "Blog"
      folder: "contents/blog"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      preview_path: "blog/{{fields.slug}}"
      fields:
          - {
                label: "Template",
                name: "template",
                widget: "hidden",
                default: "post",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Banner", name: "banner", widget: "image" }
